### ISSUE TITLE
Introduction to VueJS

### ISSUE THREAD

**Issue by couellet** [Winnipegjs/talks#10]
# ⚠️ IMPORTANT

> We ask you to please complete as many questions as possible to help us know more abour your talk and we'll use this information
when we create the meetup.com event. This way we won't have to contact you many times. Thanks in advance.

### Title
Introduction to VueJS

### Description
An introduction to Vue, a progressive framework for building user interfaces. I'll show you the basics of Vue and how it can be easily integrated into an existing codebase. The talk will contain some live coding ;) I'll also give you my takeaways from the VueConf that happened in Toronto on Nov 15-16.

### About the speaker
* **Bio**: I'm Charles Ouellet, from Quebec city but living in Winnipeg at the moment. I work at Snipcart as a developer and co-founder.

* **Winnipegjs Slack user**: Charles Ouellet
* **Twitter user**: couellet
* **Other users**: couellet on Github

### Extra

* **Do you already have this talk?**: No, not yet but I'll be working on it this week and over the weekend. 
* **In which month could your give this talk?:** November

> Please let us know if you need anything in especial to give your talk and we'll try to provide it or help you get it. This way we can plan in advance.

Thanks for sharing and hope to see your talk soon!
Winnipeg.js Team

**Comment by nisnardi** [comment]
This talk has been selected for November event

**Comment by nisnardi** [comment]
Thanks!! it was great having you talking!!
