### ISSUE TITLE
Building Your Graphql Server with Prisma

### ISSUE THREAD

**Issue by nnajiabraham** [Winnipegjs/talks#11]
### Description
Prisma is a strongly typed access layer for your database, think of it somewhat as an ORM, so it tries to solve a similar problem but it has a lot more features and it's also a lot more powerful than traditional ORM. Prisma replaces traditional ORMs and custom data access layers with a universal database abstraction used via the Prisma client. It is used to build GraphQL servers, REST APIs & more. Prisma client for various languages such as JavaScript, TypeScript, Flow, Go.

### About the speaker

* **Bio**: * Abraham Nnaji is a passionate developer, musician and an adventure driven developer. 
* **Winnipegjs Slack username**: nnajiabraham
* **Twitter**: https://twitter.com/nnajiabraham
* **Github**: https://github.com/nnajiabraham

### Resources
* **Presentation slides**: In Progress
* **Talk repo demo/example**: In Progress

### Extra

* **Do you already have this talk?**: partially
* **In which month could your give this talk?:** Febraury

Thanks for sharing and hope to see your talk soon!
Winnipeg.js Team

**Comment by nisnardi** [comment]
This talk will be part of our February meetup!! 🎊🎉💪🏻
