### ISSUE TITLE
Designer and Developer Responsibility

### ISSUE THREAD

**Issue by stephensulik** [Winnipegjs/talks#12]
### Title
Our Great Responsibility

### Description
As the applications we build become more and more engrained in people's lives, we need to examine our ethical responsibility in what we are building. Covering a mix of real world examples from both the physical and digital world I will go some ways we can hold ourselves accountable for the products we create.

### About the speaker

* **Bio**: Stephen Sulik is a designer, developer, and product person currently helping Priceline Partner Network build travel applications
* **Winnipegjs Slack user**: Stephen Sulik
* **Twitter user**: @stephensulik

### Extra

* **Do you already have this talk?**: No
* **In which month could your give this talk?:** Early May

* **Extra note** PPN can host this meetup as well.

**Comment by nisnardi** [comment]
Thanks, it was a great talk!
