### ISSUE TITLE
Deep dive into Vue.js Reactivity System

### ISSUE THREAD

**Issue by axe-me** [Winnipegjs/talks#13]
### Description
Reactivity system in javascript can be implemented in various ways. This talk will focus on how Vue.js get it done.

### About the speaker

* **Bio**: My name is An Xie. I'm a full stack developer at [Upfeat Media](https://www.upfeat.com/) Winnipeg, and I love programming.
* **Winnipegjs Slack user**: An Xie
* **Twitter**: @_a_x_e
* **Github**: @ShaneXie

### Resources
* **Presentation slides**: https://docs.google.com/presentation/d/1ir2WQIrH6Z4v2zilbxVD_2n7m5cm2gUDTNQRRpty3I4/edit?usp=sharing
* **Talk repo demo/example**: see codepen links in slides

**Comment by nisnardi** [comment]
This talk was part of our April event. Thanks!!!
