### ISSUE TITLE
 Building a React Component Library

### ISSUE THREAD

**Issue by James300** [Winnipegjs/talks#14]
### Title

Building a React Component Library for the whole ~Family~ Company

### Description

How to build a React component library that is shared by multiple teams in order to improve numerous things such as reusability and scalability. As well as, what pitfalls to avoid while developing such a project.

### About the speaker

* **Bio**: My name is James Stewart. I graduated from the University of Manitoba with a Computer Science degree and I currently work at Priceline Partner Network as a Full Stack Software Developer.
* **Winnipegjs Slack user**: @JamesStewart

### Extra

* **Do you already have this talk?:** No.
* **In which month could your give this talk?:** Early May with my friend Stephen
* **Extra note:** PPN can host this meetup as well.

**Comment by nisnardi** [comment]
Thanks for sharing, we learned a lot and hope we get an update soon.
