### ISSUE TITLE
What is SEO? 

### ISSUE THREAD

**Issue by Gihan05** [Winnipegjs/talks#15]
### **Title**

What is SEO? 

### **Description** 
Is SEO a fake thing invented by Google to manually punish your website and torment the life of developers? 

In this talk I will explain the basics about SEO
- What is SEO ?
- How Google crawls and index a website? 
- How we can use SEO and when it's the right time? 
- Different types of SEO

### **About the speaker**

My name is Gihan, I graduated in marketing in 2012 in Brazil, pursued my journalism career for a while until I realized that if I don't followed the best practices from Google my articles would possibly never rank and no one will never read it. 
I discovered the SEO world and now I'm in love with it. Nowadays I work as an SEO specialist at SkipTheDishes.   

You can always find me on twitter: @Gihkiara  

### Extra
*Do you already have this talk?*: no. 

Thanks for sharing and hope to see your talk soon!
Winnipeg.js Team

**Comment by nisnardi** [comment]
This talk was part of our April event. Thanks!!!
