### ISSUE TITLE
JAMstack, a new way to build websites

### ISSUE THREAD

**Issue by couellet** [Winnipegjs/talks#16]
### Title
JAMstack, a new way to build websites

### Description
I'm gonna to show what is JAMstack (Javascript API markup) and why you should keep an eye on this new website development trend.

### About the speaker

* **Bio**: I'm Charles Ouellet, co-founder and developer at Snipcart. I've been working on the web for the past 12 years, I love Javascript, VueJS and C# ;)

* **Winnipegjs Slack user**: Charles Ouellet 
* **Twitter user**: [couellet](https://twitter.com/couellet)
* **Other users**: [Github](https://github.com/couellet)

### Resources
* **Presentation slides**: TBA

### Extra

* **Do you already have this talk?**: No
* **In which month could your give this talk?:** July 2019

**Comment by nisnardi** [comment]
We miss you and thanks for always giving great talks. Hope we see you soon!
