### ISSUE TITLE
 Sentry: Error reporting after the fact

### ISSUE THREAD

**Issue by AxelAli** [Winnipegjs/talks#17]
### Title
Sentry: Error reporting after the fact

### Description
Hands on demo on how to add sentry to an existing app. Plus some extras to make error reporting more meaningful

### About the speaker

* **Bio**:Axel Ali, Fullstack Software Developer, Worked in many parts of Latin America, Skills include machine learning and robotics. 
* **Winnipegjs Slack user**: Axel Ali
* **Other users**: https://github.com/AxelAli https://www.linkedin.com/in/axel-ali/

### Resources
* **Presentation slides**: (Not ready yet) https://docs.google.com/presentation/d/1cwHRMbHQmZyAK5aAnLN5y0VuqbPFUiF6uO_dtctbVco/edit?usp=sharing
* **Talk repo demo/example** TBD

### Extra

* **Do you already have this talk?**: Finishing with Screenshots
* **In which month could your give this talk?:** ASAP

**Comment by nisnardi** [comment]
Thanks for a great talk!
