### ISSUE TITLE
Micro frontends - There is any valid reason to use it?

### ISSUE THREAD

**Issue by kleyson** [Winnipegjs/talks#18]
### Title
Micro frontends - There is any valid reason to use it?

### Description
We will talk about Micro frontends, what it is, what the community is saying about it, approaches to use, discuss why you would use, and show the use case at SkipTheDishes.
 
### About the speaker

* **Bio**: Kleyson Prado, Bsc in Computer Science and specialized in Software Engineering and e-Learning, I code for a living, currently working at SkipTheDishes...
* **Winnipegjs Slack user**: @kleyson
* **Twitter user**: @kleysonprado
* **Other users**: @kleyson at github and [kleysonprado](https://www.linkedin.com/in/kleysonprado/) at linkedin.

### Resources
* **Presentation slides**: Working on it.
* **Talk repo demo/example**: Not applicabe.

### Extra

* **Do you already have this talk?**: yes
* **In which month could your give this talk?:**  Next available event.

**Comment by nisnardi** [comment]
Thanks for a great talk and hope we have you as a speaker soon ❤️ 👏
