### ISSUE TITLE
Nodejs, Serverless, and Monorepo Oh My!

### ISSUE THREAD

**Issue by darrencapner** [Winnipegjs/talks#20]
### Title
Nodejs, Serverless, and Monorepo Oh My!

### Description
The way we deploy applications yesterday is changing today and will keep changing going into tomorrow. This does not mean we always need new techniques. Looking at design patterns and code structure pioneered in years past in a new way may be the way we move into the future. We'll be using Javascript running on Nodejs to see how we build with a code first mindset. To power this approach, we'll be leveraging Serverless, AWS platform and the growing in popularity monorepo pattern.

### About the speaker

* **Bio**: Darren Capner is a full stack developer, looking at the new and the old to improve his understanding and build solid solutions. He has his Computer Science Bachelor degree from the U of M. He currently works within the Innovation Lab of Wawanesa Insurance helping prove out potential solutions to key business problems.
* **Winnipegjs Slack user**: darrencapner

### Resources
* **Presentation slides**: In Development
* **Talk repo demo/example**: In Development

### Extra

* **Do you already have this talk?**: no
* **In which month could your give this talk?:** December

**Comment by nisnardi** [comment]
Thanks for doing this!! 👏
