### ISSUE TITLE
Balloon Battle - A multiplayer game using js and firebase

### ISSUE THREAD

**Issue by xandecmartins** [Winnipegjs/talks#22]
### Title
Balloon Battle - A multiplayer game using js and firebase

### Description
In order to bring a little bit of fun, let’s talk about the game area. During the presentation we gonna talk about game development, physics behind the game, implement a feature by live coding and also make a demonstration with the audience. 

As we’re talking about game, the 1st place will win a special prize.

### About the speakers

Alexandre is a Software Engineer with 15 years programming experience in delivering enterprise software. Skilled in implementing complex software programs in Java with knowledge in back-end and front-end. Recently making a move to the JS world and is currently working at SkipTheDishes as Senior Technology Manager. He has 6 years of experience as professor of subjects like OOP, data-structures, artificial intelligence and distributed systems.
Twitter: @xandecmartins

### Resources
Presentation slides: In progress
Talk repo demo/example: https://github.com/xandecmartins/balloonbattle

### Extra

Do you already have this talk?: no
In which month could your give this talk?: January

**Comment by nisnardi** [comment]
Thanks for your talk!
