### ISSUE TITLE
Automated Testing in Javascript

### ISSUE THREAD

**Issue by yagudaev** [Winnipegjs/talks#3]
### Title
Automated Testing in Javascript

### Description
Automated Testing is an important tool of ensuring the quality and durability of software. Until recently however, writing tests in Javascript has been so painful very few would go through the trouble. Thanks to modern tools like Jest and Cypress, this is no longer true. In this talk we will talk about how to write tests, the thinking behind tests and what level of test is appropriate.  

### About the speaker

* **Bio**: Michael runs Nano 3 Labs, a digital product development studio specializing in React, React Native and Ruby on Rails development. He has been writing code professionally for close to a decade now. He loves contributing to Open Source, building beautiful products and snowboarding. A University of Manitoba CS graduate and one of the early co-founders of Winnipeg.js.
* **Winnipegjs Slack user**: N/A.
* **Twitter user**: yagudaev(https://twitter.com/WinnipegJS)
* **Other users**: https://github.com/yagudaev

### Resources
* **Presentation slides**: N/A
* **Talk repo demo/example**: N/A

### Extra

* **Do you already have this talk?**: no, still writing it
* **In which month could your give this talk?:** Sep 12, 2018
> Please let us know if you need anything in especial to give your talk and we'll try to provide it or help you get it. This way we can plan in advance.
Just projector and connectors for USB-C (latest gen MacBookPro)

Thanks for sharing and hope to see your talk soon!
Winnipeg.js Team

**Comment by nisnardi** [comment]
This talk was part of the September event. Thanks!
