### ISSUE TITLE
Jest

### ISSUE THREAD

**Issue by lddv** [Winnipegjs/talks#4]
### Title
Jest

### Description
In this talk, I explore some of the history, motivations that led to the testing framework creation, some examples and features that it uses. There is also a quick look over performance options for React apps.

### About the speaker

* **Bio**: Leonardo is a React Developer at SkipTheDishes, Winnipeg. He likes to play soccer with friends, play the drums whenever he has the chance, read the Bible, and talk about many topics with interesting people. He has a Bachelor's Degree in Information Systems.
* **Winnipegjs Slack user**: @lddv
* **Twitter user**: @ldvasc
* **Other users**: https://github.com/lddv

### Resources
* **Presentation slides**: [Presentation](https://docs.google.com/presentation/d/1pXIV1FLbx2jS3iWAs6l4iE-T7QhI0_CiaDbZhVh4bBY/edit?usp=sharing) - In progress
* **Talk repo demo/example**: Not up yet, will decide if there is relevant code to share.

### Extra

* **Do you already have this talk?**: no, in progress.
* **In which month could your give this talk?:** Mid October onwards.

> Please, provide HDMI cable or DVI / VGA adapter for MacBook Pro early 2013

**Comment by nisnardi** [comment]
This talk has been scheduled for October

**Comment by nisnardi** [comment]
Thanks Leo and we look forward having you speak again soon!
