### ISSUE TITLE
GraphQL: By Himanshi

### ISSUE THREAD

**Issue by hjp2412** [Winnipegjs/talks#5]
**Title**
GraphQL vs REST API

**Description**

This is an introductory GraphQL talk to show how the query language works, the new way to think about API. For Instance, eliminating over/under fetching, reducing number of API calls and eliminate extra lines of code.

**Motivation**

I used to work for an accounting firm as a software developer. I worked on client and server side logc of payroll, subsistence, PVL and Per Diem, etc. For all of it, I have to create lots of utils function to calculate CPP, EI and etc. As a result, maintenance and readability of code became expensive. As a solution, we replace our api call with GraphQL.

* **Bio**: 
Himanshi did 4 year university in computers in India, and 2 years in Toronto from Seneca College.  She is working as software developer at skipTheDishes in customer post team.

**Comment by nisnardi** [comment]
This talk has been scheduled for October

**Comment by nisnardi** [comment]
Thanks Himanshi and we look forward having you speak again soon!
