### ISSUE TITLE
Talk Proposal:  Storytelling on JS

### ISSUE THREAD

**Issue by AxelAli** [Winnipegjs/talks#6]
### Title
Storytelling on JS

### Description
General talk on my JS game engine for visual novels and discussions about how to make frameworks for other people to use.

### About the speaker

* **Bio**: Axel Ali, Fullstack Software Developer, Worked in many parts of Latin America, Skills include machine learning and robotics
* **Winnipegjs Slack user**: Axel Ali
* **Other users**: https://linkedin.com/in/axel-ali/ , https://github.com/AxelAli

### Resources
* **Presentation slides**: TBD
* **Talk repo demo/example**: TBD

### Extra

* **Do you already have this talk?**: No
* **In which month could your give this talk?:** Next Available

**Comment by nisnardi** [comment]
This talk has been selected for November event

**Comment by nisnardi** [comment]
Thanks, it was great having you talk at Winnipeg.js!! 👍
