### ISSUE TITLE
Ember - A framework for ambitions web developers

### ISSUE THREAD

**Issue by brett-anderson** [Winnipegjs/talks#8]
### Title
Ember - A framework for ambitions web developers

### Description
This talk is about the javascript framework Ember. I will walk though the basics, pros and cons of the framework, and do some live coding to create a basic ember app.
### About the speaker

* **Bio**: I'm a full-stack engineer working remotely for a company called [Domain7](https://www.domain7.com) based in Vancouver. I am part of the custom development team, where we build applications primarily using react and rails.
In my spare time I like to curl and play hockey. I have a Bachelor of Arts from the UofM, and am a graduate of the BIT program from Red River College. I grew up in rural Manitoba.
* **Winnipegjs Slack user**: @brettanderson16
* **Twitter user**: @brettanderson16

### Resources
* **Presentation slides**: not created yet
* **Talk repo demo/example**: none yet

### Extra

* **Do you already have this talk?**: not yet, working on it.
* **In which month could your give this talk?:** I could probably give this talk in December onwards

**Comment by nisnardi** [comment]
👍

**Comment by nisnardi** [comment]
This talk will be part of our February meetup!! 🎊🎉💪🏻

**Comment by nisnardi** [comment]
Thanks for a great talk!!!
