### ISSUE TITLE
React & Typescript: writing maintainable and scalable apps

### ISSUE THREAD

**Issue by schettino** [Winnipegjs/talks#9]
### Description
Nowadays typescript has gotten more attention than ever and it's possible to see how this is shaping our community in a good way. If you use VSCode, it'll try to fetch typedefs for the libraries on your project and improve your development experience. Create React App already supports it out of the box, Babel can even transpile it. On this talk we're going to discuss about the importance of using a superset of javascript and how we can leverage it to write more reliable and readable code, eliminating categories of possible bugs and writing type definitions that just doesn't trick ourselves.

### About the speaker

* **Bio**: Matheus Schettino is a passionate developer, musician and life enthusiast. His last project helps musicians to share their work (https://wwwgruvi.com.br) and he's currently working on getting [react-i18next](https://github.com/i18next/react-i18next) improved.
* **Winnipegjs Slack user**: schettino
* **Other users**: https://github.com/schettino

### Resources
* **Presentation slides**: in progress
* **Talk repo demo/example**: in progress

### Extra

* **Do you already have this talk?**: partially
* **In which month could your give this talk?:** December

Thanks for sharing and hope to see your talk soon!
Winnipeg.js Team

**Comment by nisnardi** [comment]
Hi, I would like to know if you're still available to give this talk and if so, when would you like to do it. Thanks in advance

**Comment by nisnardi** [comment]
Please let us know if we should close this talk. Thanks
